### ISSUE TITLE
Do we need breeze-natives?

### ISSUE THREAD

**Issue by danielkorzekwa** [danielkorzekwa/bayes-scala-gp#3]
- the same question for bayes-scala project,
- look here too: https://github.com/fommil/netlib-java/issues/89

**Comment by fommil** [comment]
I'd say **no**. They are declared optional so that end users can enable them if it makes sense for their deployment and usecase.

**Comment by danielkorzekwa** [comment]
no, natives slows down breeze for small vector/matrices, excluding netlib-natives makes everything a bit faster, about 10-20%,
